import { config } from "@keystone-6/core";
import {
  Activity,
  ChampionWinrate,
  Duo,
  Constant,
  Event,
  Game,
  Objective,
  PickBan,
  Player,
  PlayerEndOfGameStat,
  PlayerItem,
  PlayerItemEvent,
  PlayerKill,
  PlayerRune,
  PlayerSkillLevelUpEvent,
  PlayerSnapshot,
  PlayerWardEvent,
  Position,
  Profile,
  SeedIdentifier,
  Source,
  Team,
  TeamBuildingKill,
  TeamMonsterKill,
  RuneSelection,
  RuneStyle,
} from "./schemas";

export default config({
  server: {
    cors: { credentials: false },
  },
  db: {
    provider: "postgresql",
    url: process.env.DATABASE_URL,
  },
  images: {
    upload: "local",
    local: {
      storagePath: "public/images",
      baseUrl: "/images",
    },
  },
  graphql: {
    playground: "apollo",
  },
  ui: {
    isAccessAllowed: () => true,
  },
  lists: {
    Activity,
    ChampionWinrate,
    Duo,
    Constant,
    Event,
    Game,
    Objective,
    PickBan,
    Player,
    PlayerEndOfGameStat,
    PlayerItem,
    PlayerItemEvent,
    PlayerKill,
    PlayerRune,
    PlayerSkillLevelUpEvent,
    PlayerSnapshot,
    PlayerWardEvent,
    Position,
    Profile,
    SeedIdentifier,
    Source,
    Team,
    TeamBuildingKill,
    TeamMonsterKill,
    RuneSelection,
    RuneStyle,
  },
});
